### ISSUE TITLE
Подготовить сравнительную характеристику библиотек

### ISSUE THREAD

**Issue by Mozzarella123** [Students-of-the-city-of-Kostroma/16ISa#3]
Составить сравнительный анализ библиотек. Таблица, где строки - библиотеки, столбцы сравниваемые характеристики

**Comment by ValyaBuldozer** [comment]
https://docs.google.com/spreadsheets/d/1nybVdgdCSkq8we0gCsOXnuLPT1SB36NO_g1FgniW-KI/edit#gid=0

**Comment by Mozzarella123** [comment]
Доработать критерии оценки библиотек, добавить краткое описание каждой,

**Comment by Mozzarella123** [comment]
Пример сравнения https://habr.com/post/313686/
https://github.com/danielpalme/IocPerformance
