### ISSUE TITLE
Отсутствие ограничения на количество операторов

### ISSUE THREAD

**Issue by blinker44** [Students-of-the-city-of-Kostroma/16ISa#63]
Что: Происходит подсчет
Где: MultiplicationDivisionCalc_9
Когда: При вводе выражения с 500 операторами

**Comment by YuriSilenok** [comment]
@blinker44 Название бага должно говрить о причинах найденого дефекта. Ознакомьтесь с этими статьями.
[Как правильно составлять баг-репорты](https://habr.com/post/156099/)
[10 правил хорошего тона при описании багов](https://habr.com/company/docsvision/blog/264163/)

**Comment by ValyaBuldozer** [comment]
Исправить : класс MathCore, метод Calculate(string) - добавить проверку входной строки на количество вхождений следующих символов " ( ) ^ + - * / " если меньше 50 выкидывать ArgumentException.
@slon2015 ветка Task#63
